project:
  type: website
  output-dir: ../docs
  execute-dir: project

website:
  title: "Munich Unemployment: A 24-Year Spatial and Demographic Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: report.qmd
        text: Statistical Report
      - href: proposal.qmd
        text: Proposal
      - href: reflection_log.qmd
        text: Reflection Log
      - about.qmd

format:
  html:
    code-fold: true
    code-summary: "Show code"
    code-line-numbers: "Show code"
    code-copy: hover
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



